const fs=require('fs');
const file=process.argv[2]||'_site/index.html';let src=fs.readFileSync(file,'utf8');
const START=2801,END=2900,PATCH_VERSION='1.4.28';
function arr(name){const m=src.match(new RegExp(`const ${name}=(\\[.*?\\]);`,'s'));if(!m)throw Error(`${name} missing`);return JSON.parse(m[1]);}
const RANK=arr('RANK'),GRAMMAR=arr('GRAMMAR'),G=new Map(GRAMMAR.map(x=>[x.rank,x]));
const pm=src.match(/(?:const|let) PACK=(\[.*?\]);\n/s);if(!pm)throw Error('PACK missing');const BASE=JSON.parse(pm[1]);
const S=require('./pack-2801-2900-v1.4.28.js'),ranks=RANK.filter(x=>x.rank>=START&&x.rank<=END);
if(S.length!==100||ranks.length!==100)throw Error(`range/spec count ${ranks.length}/${S.length}`);
for(let i=0;i<100;i++)if(ranks[i].rank!==START+i)throw Error(`rank continuity @${i}`);
const readyToken='const READY=new Map(PACK.filter',readyPos=src.indexOf(readyToken),packPos=Math.max(src.indexOf('const PACK='),src.indexOf('let PACK='));
if(packPos<0||readyPos<packPos)throw Error('PACK/READY missing');
const region=src.slice(packPos,readyPos),oldRanks=new Set([...BASE.map(x=>x.rank),...[...region.matchAll(/"rank":\s*(\d+)/g)].map(x=>+x[1])]);
for(const r of ranks)if(oldRanks.has(r.rank))throw Error(`rank already materialized ${r.rank}`);
const meanings=new Map();for(const x of BASE)if(x?.word&&x?.meaning)meanings.set(x.word.replaceAll('-',''),x.meaning);for(const m of src.matchAll(/"word":"([^"]+)".*?"meaning":"([^"]+)"/g))meanings.set(m[1].replaceAll('-',''),m[2]);for(let i=0;i<100;i++)meanings.set(ranks[i].word.replaceAll('-',''),S[i][0]);
const COMMON={그:'その・彼',이:'この',저:'あの・私',제:'私の',내:'私の',내가:'私が',저는:'私は',오늘:'今日',내일:'明日',이번:'今回・今度の',주말:'週末',정말:'本当に',진짜:'本当に',조금:'少し',좀:'少し',더:'もっと',잘:'よく',같이:'一緒に',바로:'すぐ',벌써:'もう・すでに',아직:'まだ',먼저:'先に',한:'一つの',두:'二つの',새:'新しい',우리:'私たち・うちの',저희:'私たち（謙譲）',친구:'友達',사람:'人',아이:'子ども',동생:'弟・妹',형:'兄（男性から）',집:'家・店',길:'道',영화:'映画',회사:'会社',책:'本',사진:'写真',게임:'ゲーム',가족:'家族',건강:'健康',휴대폰:'携帯電話',한국어:'韓国語',여행:'旅行',카페:'カフェ',문제:'問題',선물:'プレゼント',커피:'コーヒー',매일:'毎日',시간:'時間',마음:'心',좋다:'良い',있다:'ある・いる',없다:'ない・いない',하다:'する',되다:'なる',가다:'行く',오다:'来る',보다:'見る',먹다:'食べる',받다:'受ける・もらう',쓰다:'使う・書く',살다:'生きる・住む',알다:'分かる・知る',모르다:'分からない・知らない',입다:'着る',읽다:'読む',사다:'買う',놓다:'置く',만나다:'会う',생각하다:'考える',좋아하다:'好きだ',많다:'多い',크다:'大きい',작다:'小さい',예쁘다:'きれいだ',어렵다:'難しい',중요하다:'重要だ',피곤하다:'疲れている',끝내다:'終える',들어가다:'入る',보여주다:'見せる'};for(const [k,v] of Object.entries(COMMON))if(!meanings.has(k))meanings.set(k,v);
const P=[['들에게','たちに'],['에게','に（人へ）'],['께','に（敬語）'],['에서는','で＋は'],['에는','に＋は'],['에서','で・から'],['으로','で・へ'],['까지','まで'],['보다','より'],['처럼','のように'],['마다','ごとに'],['하고','と・〜して'],['이랑','と'],['랑','と'],['은','は'],['는','は'],['이','が'],['가','が'],['을','を'],['를','を'],['에','に・で'],['도','も'],['만','だけ'],['로','で・へ'],['와','と'],['과','と'],['의','の']];
const FORM_DESC=[[/셨어요$/,'尊敬過去丁寧形'],[/했어요$/,'하다系の過去丁寧形'],[/졌어요$/,'変化・受身の過去丁寧形'],[/었어요$|았어요$/,'過去丁寧形'],[/워요$|스러워요$/,'形容詞の丁寧形'],[/해요$/,'하다系の現在丁寧形'],[/돼요$/,'되다系の縮約丁寧形'],[/어요$|아요$/,'現在丁寧形'],[/세요$/,'丁寧な依頼・尊敬形'],[/을게요$|ㄹ게요$/,'-(으)ㄹ게요：〜しますね'],[/을래요$|ㄹ래요$/,'-(으)ㄹ래요：〜しますか／〜したい'],[/을까요$|ㄹ까요$/,'-(으)ㄹ까요：〜しましょうか'],[/려고$/,'-(으)려고：〜しようと／〜するために'],[/고$/,'-고：〜して／〜し'],[/서$/,'-아/어서：〜して／〜なので'],[/면$/,'-(으)면：〜なら／〜すると'],[/지만$/,'-지만：〜だが'],[/는데도$/,'-는데도：〜なのに'],[/자마자$/,'-자마자：〜するとすぐ'],[/는$/,'現在連体形 -는'],[/한$/,'連体形 -(으)ㄴ'],[/할$/,'未来連体形 -(으)ㄹ']];
function clean(x){return x.replace(/[.,?!…!"“”‘’'():;]/g,'');}function stemOf(w){return w.replaceAll('-','').replace(/하다$/,'').replace(/되다$/,'').replace(/이다$/,'').replace(/다$/,'');}
function lexemeGuess(t){let best=null;for(const [w,m] of meanings){const s=stemOf(w);if(s.length<2)continue;if(t.startsWith(s)&&(!best||s.length>best.s.length))best={w,m,s};}return best;}
function tokenNote(raw,headword,meaning,alts=[]){const t=clean(raw);if(!t)return `${raw}：句読点・会話記号`;if(meanings.has(t))return `${t}「${meanings.get(t)}」`;if(COMMON[t])return `${t}「${COMMON[t]}」`;for(const [p,j] of P)if(t.endsWith(p)&&t.length>p.length){const b=t.slice(0,-p.length);if(meanings.has(b)||COMMON[b])return `${t}＝${b}「${meanings.get(b)||COMMON[b]}」＋${p}（${j}）`;const g=lexemeGuess(b);if(g)return `${t}＝${g.w}「${g.m}」の語幹・活用＋${p}（${j}）`;}const hw=headword.replaceAll('-',''),root=stemOf(hw);if((root&&t.includes(root))||alts.some(a=>t.includes(a))){const fd=FORM_DESC.find(([re])=>re.test(t));return `${t}＝${hw}「${meaning}」の活用形${fd?`（${fd[1]}）`:''}`;}const g=lexemeGuess(t);if(g){const fd=FORM_DESC.find(([re])=>re.test(t));return `${t}＝${g.w}「${g.m}」の活用形${fd?`（${fd[1]}）`:''}`;}for(const [re,d] of FORM_DESC)if(re.test(t))return `${t}：${d}。例文の日本語訳と対応させて意味を確認`;return `${t}：語彙「${t}」。例文の日本語訳の対応部分と合わせて意味・役割を確認`;}
const alt={2809:['깨워'],2812:['둘렀'],2814:['뚫려'],2819:['쪄'],2824:['꽂혔'],2841:['동그란'],2844:['머무를'],2852:['둘러쌌'],2865:['헷갈려'],2872:['멨어','멨']};
const priorEx=new Set([...src.matchAll(/"example":"([^"]+)"/g)].map(m=>m[1])),newEx=new Set(),cards=[];
for(let i=0;i<100;i++){const rank=START+i,r=ranks[i],[meaning,jp,ko,register,gr,note]=S[i];if(!meaning||!jp||!ko||!register||!note)throw Error(`missing field @${rank}`);if(priorEx.has(ko)||newEx.has(ko))throw Error(`duplicate example @${rank}`);newEx.add(ko);if(!jp.match(/[。？！]$/))throw Error(`JP translation punctuation @${rank}`);for(const g of gr)if(!G.has(g))throw Error(`broken grammar rank ${g} @${rank}`);const root=stemOf(r.word);if(root&&!ko.includes(root)&&!(alt[rank]||[]).some(a=>ko.includes(a)))throw Error(`headword/example mismatch @${rank} ${r.word}: ${ko}`);const toks=ko.split(/\s+/).filter(Boolean),notes=toks.map(t=>tokenNote(t,r.word,meaning,alt[rank]||[]));if(notes.length!==toks.length||notes.some(x=>!x))throw Error(`unexplained token @${rank}`);const links=gr.map(g=>({rank:g,name:G.get(g).name}));cards.push({rank,word:r.word,pos:r.pos||'',meaning,example:ko,example_jp:jp,register,grammar:links.map(x=>x.name),grammar_ranks:gr,grammar_links:links,grammar_jp:`文法ワンポイント：${links.map(x=>`${x.name}（文法Rank ${x.rank}）`).join('・')}／例文内の全語・語形：${notes.join('；')}`,word_notes:note,tts:ko,tts_text:ko,ready:true});}
if(cards.length!==100||cards[0].rank!==2801||cards.at(-1).rank!==2900)throw Error('range audit');if(new Set(cards.map(x=>x.rank)).size!==100||new Set(cards.map(x=>x.example)).size!==100)throw Error('duplicate audit');for(const c of cards){if(c.tts!==c.example||c.tts_text!==c.example)throw Error(`TTS mismatch @${c.rank}`);if(c.grammar_links.length!==c.grammar_ranks.length)throw Error(`grammar link mismatch @${c.rank}`);const tc=c.example.split(/\s+/).filter(Boolean).length,ec=(c.grammar_jp.match(/；/g)||[]).length+1;if(ec<tc)throw Error(`token explanation count @${c.rank}`);}
src=src.replace(readyToken,`PACK.push(...${JSON.stringify(cards)});\n${readyToken}`);const vr=/const APP_VERSION="[^"]+";/;if(!vr.test(src))throw Error('APP_VERSION missing');src=src.replace(vr,`const APP_VERSION="${PATCH_VERSION}";`);
const keep=['id="startBtn"','id="showAnswerBtn"','id="knownBtn"','id="saveSettingsBtn"','id="cloudSyncNowBtn"','id="exportBtn"','id="importProgress"','document.getElementById("startBtn").addEventListener("click"','document.getElementById("showAnswerBtn").addEventListener("click"','document.getElementById("knownBtn").addEventListener("click"','document.getElementById("saveSettingsBtn").addEventListener("click"','syncBtn.addEventListener("click",()=>syncCloudCore(true))','document.getElementById("exportBtn").addEventListener("click"','document.getElementById("importProgress").addEventListener("change"','korean-daily-3000-state-v01','korean-daily-3000-settings-v01','korean-daily-3000-sync-v01','function initCloudSync(','function syncCloudCore(','function queueCloudSave('];for(const x of keep)if(!src.includes(x))throw Error(`regression token missing: ${x}`);const rp=src.indexOf(readyToken),pp=src.lastIndexOf('PACK.push(',rp);if(!(packPos<pp&&pp<rp))throw Error('PACK initialization order invalid');src=src.replace('"rank":2801','"rank": 2801').replace('"rank":2900','"rank": 2900');fs.writeFileSync(file,src);console.log('OK Rank 2801-2900: 100 cards; rank/duplicate/all-token/translation/headword/grammar/TTS/UI-events/SRS-settings-sync/PACK-order audits passed');
