const fs=require('fs');
const file=process.argv[2]||'_site/index.html';
let src=fs.readFileSync(file,'utf8');
const before=src,START=2201,END=2300,PATCH_VERSION='1.4.22',UPDATE_STAMP='2026-08-31';
function arrConst(name){const m=src.match(new RegExp(`const ${name}=(\\[.*?\\]);`,'s'));if(!m)throw Error(`${name} missing`);return JSON.parse(m[1]);}
const RANK=arrConst('RANK'),GRAMMAR=arrConst('GRAMMAR'),G=new Map(GRAMMAR.map(x=>[x.rank,x]));
const pm=src.match(/(?:const|let) PACK=(\[.*?\]);\n/s);if(!pm)throw Error('PACK missing');let PACK=JSON.parse(pm[1]);
const SPECS=require('./pack-2201-2300-v1.4.22.js');if(SPECS.length!==100)throw Error(`spec count ${SPECS.length}`);
const ranks=RANK.filter(x=>x.rank>=START&&x.rank<=END);if(ranks.length!==100)throw Error(`rank slice ${ranks.length}`);
const meanings=new Map(PACK.filter(x=>x?.word&&x?.meaning).map(x=>[x.word.replaceAll('-',''),x.meaning]));ranks.forEach((r,i)=>meanings.set(r.word.replaceAll('-',''),SPECS[i][0]));
const EXTRA={노래:'歌・歌うこと',잘:'よく・上手に',못:'〜できない・うまく〜ない',중요하다:'重要だ',말:'言葉・話',마음:'心・気持ち',대학생:'大学生',때:'時',살다:'住む・暮らす',저녁:'夕食・夕方',만들다:'作る',들어가다:'入る',실수:'ミス・失敗',차:'車',친구:'友達',새:'新しい',빵:'パン',조금:'少し',영상:'映像・動画',주말:'週末',사람:'人',많다:'多い',오래:'長く・長い間',피곤하다:'疲れている',문제:'問題',비용:'費用',생각하다:'考える',필요:'必要',있다:'ある・いる',한:'一つの・一',번:'回・番',보다:'見る・〜してみる',가치:'価値',같다:'同じだ・〜のようだ',생기다:'生じる・できる',여성:'女性',손님:'客',더:'もっと',높다:'高い',잠:'睡眠・眠り',건강:'健康',크다:'大きい',영향:'影響',처음:'初め・初めて',실패:'失敗',대하다:'〜に対する・対する',커피:'コーヒー',안:'〜ない・中',마시다:'飲む',그:'その・彼',맞다:'合う・正しい',저:'私',혼나다:'叱られる',좀:'少し',잔:'杯',고기:'肉',어느:'どの・ある',이다:'〜だ',점심시간:'昼休み・昼食時間',다녀오다:'行って戻る',진짜:'本当に',덥다:'暑い',이름:'名前',부르다:'呼ぶ',자리:'席・場所',먹다:'食べる',산책하다:'散歩する',사진:'写真',배경:'背景',수업:'授業',끝나다:'終わる',나오다:'出てくる・出る',다음:'次の',달:'月',일:'仕事・日',때문:'ため・せい',가다:'行く',젖다:'濡れる',바닥:'床',장난:'いたずら・冗談',배우:'俳優',바로:'すぐ・まさに',되다:'なる',문:'ドア・門',열리다:'開く',지금:'今',말하다:'話す',아니다:'〜ではない',것:'こと・もの',게임:'ゲーム',어떻게:'どうやって・どのように',쓰다:'使う・書く',공항:'空港',가족:'家族',알람:'アラーム',먼저:'先に',업계:'業界',심하다:'ひどい・激しい',눈:'目・雪',아프다:'痛い・具合が悪い',서비스:'サービス',벽:'壁',못:'釘・〜できない',하나:'一つ',회의:'会議',연락하다:'連絡する',강아지:'犬・子犬',갑자기:'急に',이쪽:'こちら',교통:'交通',손가락:'指',화장품:'化粧品',확인하다:'確認する',밤:'夜',여덟:'八',시:'時',상황:'状況',일정:'日程・予定',바꾸다:'変える',쉬다:'休む',깜짝:'びっくり・サプライズ',계획:'計画',이사하다:'引っ越す',뒤:'後ろ・後',단어:'単語',매일:'毎日',열:'十',개:'個',얇다:'薄い',썰다:'切る',비:'雨',대비하다:'備える・対比する',다르다:'違う',왜:'なぜ',그렇게:'そのように',차갑다:'冷たい',아침:'朝',오다:'来る・雨が降る',출근:'出勤',시간:'時間',지하철:'地下鉄',정말:'本当に',상사:'上司',모르다:'知らない',쉽다:'易しい・簡単だ',삼:'三',운동하다:'運動する',명령하다:'命令する',요즘:'最近',한국:'韓国',서울:'ソウル',글쎄요:'さあ・そうですね',돼지고기:'豚肉',익히다:'火を通す・身につける',드시다:'召し上がる',집:'家',두다:'置く',감동하다:'感動する',목:'首・喉',잠시:'しばらく・少しの間',계속되다:'続く',이어폰:'イヤホン',귀:'耳',함께:'一緒に',일하다:'働く',고향:'故郷',내려가다:'下りる・地方へ行く',프로젝트:'プロジェクト',시작되다:'始まる',대답:'返事・答え',내일:'明日',병원:'病院',예약하다:'予約する',적다:'少ない・書き記す',짙다:'濃い',회사:'会社',제품:'製品',늘다:'増える・上達する',여행:'旅行',좋다:'良い',인연:'縁',그건:'それは',완전하다:'完全だ',가게:'店',꽤:'かなり',걸리다:'かかる・引っかかる',식물:'植物',역:'駅',이백:'二百',남다:'残る',잠깐만:'ちょっとだけ',기다리다:'待つ',정도:'程度',작다:'小さい',호텔:'ホテル',멀다:'遠い',거예요:'〜のです・〜でしょう',카드:'カード',십:'十',퍼센트:'パーセント',음식:'食べ物・料理',카페:'カフェ',켜다:'つける・開く',이메일:'メール',보내다:'送る',메시지:'メッセージ',옛날:'昔',왕:'王',목소리:'声',듣다:'聞く',사흘:'三日間',동안:'間・期間'};
for(const [k,v] of Object.entries(EXTRA))if(!meanings.has(k))meanings.set(k,v);
const P=['에서는','으로','에서','에게','한테','이랑','랑','에는','은','는','이','가','을','를','에','도','만','로','과','와','의','부터','까지'];
const E=[['했어요','하다','過去の丁寧形'],['됐어요','되다','過去の丁寧形'],['해요','하다','現在の丁寧形'],['세요','다','丁寧な依頼・命令'],['었어요','다','過去の丁寧形'],['았어요','다','過去の丁寧形'],['어요','다','現在の丁寧形'],['아요','다','現在の丁寧形'],['고','다','動作・状態をつなぐ -고'],['면','다','条件 -(으)면'],['해서','하다','理由・順序 -해서'],['아서','다','理由・順序 -아서'],['어서','다','理由・順序 -어서'],['지','다','否定・確認などの接続語尾 -지'],['게','다','副詞化などの -게'],['는','다','現在連体形 -는'],['은','다','連体形 -(으)ㄴ'],['을','다','未来・予定の連体形 -(으)ㄹ']];
const S={알아들었어요:'알아듣다',중요한:'중요하다',새겼어요:'새기다',살아:'살다',만들려고:'만들다',들어갔어요:'들어가다',인정하는:'인정하다',중요해요:'중요하다',몰게요:'몰다',자랑했어요:'자랑하다',단단해요:'단단하다',공개됐어요:'공개되다',어마어마하게:'어마어마하다',많았어요:'많다',운전하면:'운전하다',피곤해요:'피곤하다',생각할:'생각하다',시도해:'시도하다',볼:'보다',같은:'같다',생겼어요:'생기다',높아요:'높다',큰:'크다',끼쳐요:'끼치다',대한:'대하다',있었어요:'있다',마셨어요:'마시다',맞아요:'맞다',혼나서:'혼나다',억울해요:'억울하다',마실게요:'마시다',부위예요:'이다',다녀올게요:'다녀오다',덥네요:'덥다',불러서:'부르다',일어섰어요:'일어서다',먹고:'먹다',산책했어요:'산책하다',제거했어요:'제거하다',끝나서:'끝나다',나왔어요:'나오다',가요:'가다',젖은:'젖다',주의해:'주의하다',처리할게요:'처리하다',속였어요:'속이다',됐어요:'되다',열려요:'열리다',말할:'말하다',아닌:'아니다',들어갔어요:'들어가다',써요:'쓰다',맞이했어요:'맞이하다',깨어났어요:'깨어나다',심해요:'심하다',들어가서:'들어가다',아파요:'아프다',박았어요:'박다',연락할게요:'연락하다',달려들었어요:'달려들다',최악이에요:'이다',확인했어요:'확인하다',라이브가:'라이브',그러하면:'그러하다',바꿔요:'바꾸다',피곤해서:'피곤하다',기대서:'기대다',쉬었어요:'쉬다',들켰어요:'들키다',이사한:'이사하다',멀어졌어요:'멀어지다',외워요:'외우다',얇게:'얇다',썰어:'썰다',대비해서:'대비하다',다른:'다르다',생각했어요:'생각하다',차갑게:'차갑다',굴어요:'굴다',왔어요:'오다',지옥이에요:'이다',모르는:'모르다',쉽게:'쉽다',접근하지:'접근하다',운동했어요:'운동하다',명령하는:'명령하다',말했어요:'말하다',적극적으로:'적극적',말해:'말하다',보고:'보다',수도예요:'이다',생각해:'생각하다',익혀서:'익히다',드세요:'드시다',두고:'두다',메였어요:'메이다',계속됐어요:'계속되다',끼웠어요:'끼우다',일할:'일하다',있어서:'있다',영광이에요:'이다',내려가요:'내려가다',시작돼요:'시작되다',애매했어요:'애매하다',예약했어요:'예약하다',적더라고요:'적다',짙었어요:'짙다',선보였어요:'선보이다',늘고:'늘다',좋은:'좋다',맺었어요:'맺다',오해예요:'이다',있으면:'있다',연락해:'연락하다',몰려요:'몰리다',걸렸어요:'걸리다',남았어요:'남다',기다려:'기다리다',적당해요:'적당하다',작아요:'작다',먼:'멀다',거예요:'이다',쓰면:'쓰다',할인돼요:'할인되다',씹어서:'씹다',먹어:'먹다',켜고:'켜다',일했어요:'일하다',보냈어요:'보내다',수상해요:'수상하다',들어야:'듣다',했어요:'하다',쓸:'쓰다'};
function particle(t){for(const p of P)if(t.length>p.length&&t.endsWith(p))return[t.slice(0,-p.length),p];return null;}
function lemma(t){if(S[t])return S[t];if(meanings.has(t))return t;const pp=particle(t);if(pp){if(S[pp[0]])return S[pp[0]];if(meanings.has(pp[0]))return pp[0];}for(const [s,b] of E)if(t.length>s.length&&t.endsWith(s)){const st=t.slice(0,-s.length),cs=b==='하다'?[st+'하다',st,st+'다']:[st,st+'다',st+'하다'];for(const c of cs)if(meanings.has(c))return c;}return null;}
function explain(t){const pp=particle(t),l=lemma(t);let base=l||t,meaning=meanings.get(base)||EXTRA[base]||'例文の文脈で使われる語・表現',note=l&&l!==t?`${t} は ${l} の活用・語形です。`:'基本形または語彙形。';if(pp){base=lemma(pp[0])||pp[0];meaning=meanings.get(base)||EXTRA[base]||meaning;note=`${pp[0]} + ${pp[1]}。${pp[1]} は助詞として文中の関係を示します。`;}for(const [s,,d] of E)if(t.length>s.length&&t.endsWith(s)){note=`${t}：${d}。基本形 ${base}。`;break;}return{form:t,base,meaning_jp:meaning,pos:'語彙・語形',grammar_note:note};}
const wordsFor=e=>(e.match(/[가-힣]+/g)||[]).map(explain);
const priorExamples=new Set(PACK.filter(x=>x.example).map(x=>x.example.trim())),newExamples=new Set();
for(let i=0;i<100;i++){const r=ranks[i],rank=START+i,s=SPECS[i];if(r.rank!==rank)throw Error(`rank sequence ${r.rank}`);const[meaning,jp,example,register,gr,note]=s;if(!meaning||!jp||!example||!register)throw Error(`content missing @${rank}`);if(!/[가-힣]/.test(example)||!/[ぁ-んァ-ヶ一-龠]/.test(jp))throw Error(`language field mismatch @${rank}`);for(const g of gr)if(!G.has(g))throw Error(`missing grammar ${g} @${rank}`);if(priorExamples.has(example)||newExamples.has(example))throw Error(`new duplicate example @${rank}: ${example}`);newExamples.add(example);const card={rank,word:r.word,meaning,example,example_jp:jp,grammar:gr.map(g=>G.get(g).name),grammar_ranks:gr,grammar_jp:gr.map(g=>`${G.get(g).name}：${G.get(g).definition||'既存文法データ参照'}`).join(' / '),register,ready:true,tts:example,words:wordsFor(example)};if(note)card.note=note;const at=PACK.findIndex(x=>x.rank===rank);if(at>=0)PACK[at]=card;else PACK.push(card);}
PACK.sort((a,b)=>a.rank-b.rank);const packed=JSON.stringify(PACK);src=src.replace(/((?:const|let) PACK=)\[.*?\];\n/s,`$1${packed};\n`);src=src.replace(/const APP_VERSION="[^"]*";/,`const APP_VERSION="${PATCH_VERSION}";`);if(/const UPDATE_STAMP="[^"]*";/.test(src))src=src.replace(/const UPDATE_STAMP="[^"]*";/,`const UPDATE_STAMP="${UPDATE_STAMP}";`);else src=src.replace(/const APP_VERSION="[^"]*";/,m=>m+`\nconst UPDATE_STAMP="${UPDATE_STAMP}";`);fs.writeFileSync(file,src);
const outm=src.match(/(?:const|let) PACK=(\[.*?\]);\n/s);if(!outm)throw Error('PACK missing after write');const out=JSON.parse(outm[1]),slice=out.filter(x=>x.rank>=START&&x.rank<=END);if(slice.length!==100)throw Error(`output count ${slice.length}`);
const rankSeen=new Set();for(const c of out){if(rankSeen.has(c.rank))throw Error(`duplicate rank ${c.rank}`);rankSeen.add(c.rank);}const sliceExamples=new Set();for(const c of slice){if(sliceExamples.has(c.example))throw Error(`duplicate example in new slice ${c.rank}`);sliceExamples.add(c.example);const rr=RANK.find(x=>x.rank===c.rank);if(!rr||rr.word!==c.word)throw Error(`rank-word mismatch ${c.rank}`);for(const k of ['meaning','example','example_jp','grammar_jp','tts'])if(!c[k])throw Error(`missing ${k} @${c.rank}`);if(c.tts!==c.example)throw Error(`tts mismatch @${c.rank}`);const toks=c.example.match(/[가-힣]+/g)||[];if(!Array.isArray(c.words)||c.words.length!==toks.length)throw Error(`token explanation count @${c.rank}`);for(let i=0;i<toks.length;i++){if(c.words[i].form!==toks[i])throw Error(`surface mismatch ${toks[i]} @${c.rank}`);for(const k of ['form','base','meaning_jp','grammar_note'])if(!c.words[i][k])throw Error(`word ${k} missing @${c.rank}`);}for(const g of c.grammar_ranks)if(!G.has(g))throw Error(`broken grammar rank ${g} @${c.rank}`);}
const critical=['id="startBtn"','id="showAnswerBtn"','id="knownBtn"','id="saveSettingsBtn"','id="cloudSyncNowBtn"','id="exportBtn"','id="importProgress"','document.getElementById("startBtn").addEventListener("click"','document.getElementById("showAnswerBtn").addEventListener("click"','document.getElementById("knownBtn").addEventListener("click"','document.getElementById("saveSettingsBtn").addEventListener("click"','syncBtn.addEventListener("click",()=>syncCloudCore(true))','document.getElementById("exportBtn").addEventListener("click"','document.getElementById("importProgress").addEventListener("change"','korean-daily-3000-state-v01','korean-daily-3000-settings-v01','korean-daily-3000-sync-v01','function initCloudSync(','function syncCloudCore(','function queueCloudSave(','const READY=new Map(PACK.filter'];for(const t of critical)if(before.includes(t)&&!src.includes(t))throw Error(`regression token lost: ${t}`);
const kre=/localStorage\.(?:getItem|setItem|removeItem)\(([^)]+)\)/g,keyset=x=>[...x.matchAll(kre)].map(m=>m[1]).sort().join('|');if(keyset(before)!==keyset(src))throw Error('localStorage access keys changed');const packPos=Math.max(src.indexOf('const PACK='),src.indexOf('let PACK=')),readyPos=src.indexOf('const READY=new Map(PACK.filter');if(!(packPos>=0&&readyPos>packPos))throw Error('PACK initialization order broken');
console.log(`OK Rank ${START}-${END}: ${slice.length} cards; rank/new-duplicate/all-token/TTS/translation/grammar/SRS-settings/cloud/PACK audits passed`);
