const fs=require('fs');
const file=process.argv[2]||'_site/index.html';
let src=fs.readFileSync(file,'utf8');
const before=src;
const START=2101,END=2200,PATCH_VERSION='1.4.21',UPDATE_STAMP='2026-08-31';
function parseArrayConst(name){const re=new RegExp(`const ${name}=(\\[.*?\\]);`,`s`);const m=src.match(re);if(!m)throw new Error(`Cannot parse ${name}`);return JSON.parse(m[1]);}
const RANK=parseArrayConst('RANK');
const GRAMMAR=parseArrayConst('GRAMMAR');
const pm=src.match(/(?:const|let) PACK=(\[.*?\]);\n/s);if(!pm)throw new Error('Cannot parse PACK');
let PACK=JSON.parse(pm[1]);
const G=new Map(GRAMMAR.map(g=>[g.rank,g]));
const SPECS=require('./pack-2101-2200-v1.4.21.js');
if(SPECS.length!==100)throw new Error(`spec count ${SPECS.length}`);
const ranks=RANK.filter(r=>r.rank>=START&&r.rank<=END);if(ranks.length!==100)throw new Error(`rank slice ${ranks.length}`);
const meanings=new Map(PACK.filter(x=>x&&x.word&&x.meaning).map(x=>[x.word.replaceAll('-',''),x.meaning]));
ranks.forEach((r,i)=>meanings.set(r.word.replaceAll('-',''),SPECS[i][0]));
const COMMON={면접:'面接',자리:'席・場所',미리:'あらかじめ',한:'一つの・一',번:'回',본:'見る・経験する',적:'経験・こと',항상:'いつも',남:'他人・人',되도록:'なるべく',어릴:'幼い',혼자:'一人で',브랜드:'ブランド',삼:'三',층:'階',나가기:'出かけること',전에:'前に',호텔:'ホテル',방:'部屋',바다:'海',공항:'空港',친구:'友達',내년에:'来年',갈:'行く',예정:'予定',오늘은:'今日は',여섯:'六',시:'時',그림:'絵',한국에서:'韓国で',다양한:'多様な・いろいろな',문화:'文化',보고:'見て',싶어요:'〜したいです',올해도:'今年も',모두:'みんな・全員',건강하길:'健康であるよう',자세한:'詳しい',내용:'内容',확인해:'確認して',주세요:'ください',참가자:'参加者',도착했어요:'到着しました',그렇게:'そのように',저를:'私を',매일:'毎日',밤:'夜',가족의:'家族の',건강을:'健康を',위해:'〜のために',가게:'店',국내산:'韓国産・国内産',소고기:'牛肉',써요:'使います',열심히:'一生懸命',만큼:'〜ほど・〜だけ',충분한:'十分な',받고:'受けて',한국어로:'韓国語で',말할:'話す',조금:'少し',생겼어요:'生まれました・つきました',아직:'まだ',결정하기에는:'決めるには',좀:'少し',요즘:'最近',예전보다:'以前より',떨어졌어요:'落ちました',처음:'初めて',온:'来た',곳이라서:'場所なので',다음:'次の',주:'週',행사:'行事・イベント',촛불의:'ろうそくの',작은:'小さい',예뻐요:'きれいです',기온이:'気温が',삼십:'三十',도에:'度に',국이:'スープが',것:'こと・もの',같아요:'〜ようです',내일:'明日',회의에는:'会議には',꼭:'必ず',길이:'道が',막혀서:'混んでいて・塞がって',버스가:'バスが',지역에서는:'地域では',회사:'会社',강해요:'強いです',금액을:'金額を',다시:'もう一度',동생은:'弟・妹は',올해:'今年',입학했어요:'入学しました',아이의:'子どもの',정말:'本当に',빨라요:'速いです',팀:'チーム',조금:'少し',아침:'朝',햇빛이:'日差しが',안을:'中を',밝게:'明るく',늦은:'遅れた',바로:'すぐ',지금:'今',꽤:'かなり',시계를:'時計を',보니:'見ると',벌써:'もう・すでに',열두:'十二',시였어요:'時でした',프로그램은:'番組は',젊은:'若い',많아요:'多いです',끝내면:'終えると',받을:'受け取る',서울에는:'ソウルには',사흘만:'三日だけ',두:'二',명:'人',봉사단에서:'ボランティア団体で',큰:'大きい',움직이는:'動く',건:'ことは',불편해요:'不便です',의견을:'意見を',듣고:'聞いて',나서:'〜してから',결정해요:'決めます',목소리가:'声が',작아서:'小さくて',잘:'よく',못했어요:'できませんでした',물을:'水を',컵에:'コップに',천천히:'ゆっくり',사람은:'人は',요리:'料理',드라마:'ドラマ',외웠어요:'覚えました',주말:'週末',식당:'食堂・レストラン',크림을:'クリームを',바르면:'塗ると',피부가:'肌が',앞을:'前を',보고:'見て',걸어:'歩いて',아이가:'子どもが',보자:'見ると・〜すると',퀴즈:'クイズ',답을:'答えを',하나:'一つ',데:'ところ・ことに',성공했어요:'成功しました',파일을:'ファイルを',이메일로:'メールで',보내:'送って',안전에:'安全に',대한:'〜についての',조금:'少し',바닷가:'海辺',사진에:'写真に',얼굴이:'顔が',이상하게:'変に',결과를:'結果を',같이:'一緒に',그럼:'それなら',방법을:'方法を',컵이:'コップが',바닥에:'床に',떨어져서:'落ちて',오늘은:'今日は',시간을:'時間を',낼:'作る・出す',비가:'雨が',나가요:'出かけます',계단에서:'階段で',않게:'〜しないように',조심해:'気をつけて',계란말이를:'卵焼きを',살짝:'軽く',주말에:'週末に',전등을:'照明を',새것으로:'新しいものに',바꿨어요:'替えました',어젯밤에는:'昨夜は',많이:'たくさん',왔어요:'来ました・降りました',역에서:'駅で',나와:'出て',집에:'家に',갔어요:'行きました・帰りました',아이를:'子どもを',안았어요:'抱きました',생일:'誕生日',케이크를:'ケーキを',먹었어요:'食べました',여행에:'旅行に',약을:'薬を',준비했어요:'準備しました',조금씩:'少しずつ',공부하고:'勉強して',교회:'教会',목사를:'牧師を',만났어요:'会いました',약속을:'約束を',어긴:'破った',받았어요:'受けました',모르는:'知らない',단어를:'単語を',찾아봐요:'調べてみます',이런:'このような',처음이에요:'初めてです',왠지:'なんとなく',좋은:'良い',와요:'来ます',얼음이:'氷が',금방:'すぐ',내일은:'明日は',막힐:'混む・塞がる',것으로:'ものと',예상돼요:'予想されます',사람:'人',이번:'今回',학기에는:'学期には',올랐어요:'上がりました',집에서:'家で',허브를:'ハーブを',분위기가:'雰囲気が',오래:'長く',일해서:'働いて',들었어요:'入りました・湧きました',오늘:'今日',몇:'何',시에:'時に',아침에는:'朝は',개:'個',내일:'明日',경기에서:'試合で',다:'みんな・すべて',형은:'兄は',군대에:'軍隊に',가:'行って',있어요:'います',손가락에:'指に',가시가:'とげが',화가:'怒りが',나서:'出て・腹が立って',심한:'ひどい',말을:'言葉を',참석:'出席',여부를:'可否を',알려:'知らせて',이건:'これは',습관이에요:'習慣です',호텔:'ホテル',따라:'〜によって',가격이:'価格が',달라요:'違います',영화를:'映画を',보면서:'見ながら',과자를:'お菓子を',산이:'山が',여름이:'夏が',되면:'なると',아주:'とても'};
for(const [k,v] of Object.entries(COMMON))if(!meanings.has(k))meanings.set(k,v);
const particles=['에서는','으로','에서','에게','한테','이랑','랑','에는','은','는','이','가','을','를','에','도','만','로','과','와','의'];
const endings=[['했어요','하다','했어요＝하다 の過去丁寧形'],['해요','하다','해요＝하다 の現在丁寧形'],['하세요','하다','하세요＝하다＋尊敬・丁寧な依頼'],['해 주세요','하다','해 주세요＝「〜してください」'],['었어요','다','-었어요＝過去の丁寧形'],['았어요','다','-았어요＝過去の丁寧形'],['어요','다','-어요＝現在の丁寧形'],['아요','다','-아요＝現在の丁寧形'],['세요','다','-(으)세요＝丁寧な依頼・命令'],['고','다','-고＝動作・状態をつなぐ'],['면','다','-(으)면＝「〜なら／〜すると」'],['해서','하다','-해서＝理由・順序'],['아서','다','-아서＝理由・順序'],['어서','다','-어서＝理由・順序'],['지만','다','-지만＝「〜だが」'],['는지','다','-(으)ㄴ/는지＝間接疑問・不確かさ'],['지','다','-지＝否定・確認などの接続語尾'],['게','다','-게＝副詞化など'],['는','다','-는＝現在の連体形'],['은','다','-(으)ㄴ＝連体形'],['을','다','-(으)ㄹ＝未来・予定の連体形']];
const SURFACE_BASE={부리지:'욕심',확보해:'확보하다',가:'가다',긴장해요:'긴장',좋아했어요:'좋아하다',하기:'하다',써요:'쓰다',내려다볼:'내려다보다',갈:'가다',일해요:'일하다',경험해:'경험하다',빌어요:'빌다',노려보지:'노려보다',기도해요:'기도하다',받고:'받다',생겼어요:'생기다',조심스러워요:'조심스럽다',떨어졌어요:'떨어지다',참가해요:'참가하다',달했어요:'달하다',짠:'짠',참석해요:'참석하다',느려요:'느리다',강해요:'강하다',확인했어요:'확인하다',입학했어요:'입학하다',바꿨어요:'바꾸다',비춰요:'비추다',사과했어요:'사과하다',만족하고:'만족하다',시였어요:'이다',많아요:'많다',끝내면:'끝내다',머물러요:'머물다',활동하고:'활동하다',움직이는:'움직이다',결정해요:'결정하다',알아듣지:'알아듣다',쏟아:'쏟다',외웠어요:'외우다',바르면:'바르다',촉촉해요:'촉촉하다',걸어:'걷다',달려왔어요:'달려오다',맞히는:'맞히다',보내:'보내다',찍혔어요:'찍히다',분석해:'분석하다',정리했어요:'정리하다',부서졌어요:'부서지다',낼:'내다',그치면:'그치다',넘어지지:'넘어지다',뒤집어:'뒤집다',왔어요:'오다',갔어요:'가다',안았어요:'안다',대비해서:'대비하다',공부하고:'공부하다',만났어요:'만나다',어긴:'어기다',받았어요:'받다',찾아봐요:'찾아보다',녹아요:'녹다',예상돼요:'예상되다',계산해:'계산하다',올랐어요:'오르다',기르고:'기르다',묘해요:'묘하다',들었어요:'들다',와요:'오다',먹어요:'먹다',응원해요:'응원하다',박혔어요:'박히다',내뱉었어요:'내뱉다',알려:'알리다',달라요:'다르다',먹었어요:'먹다',푸르러요:'푸르다'};
function stripParticle(tok){for(const p of particles){if(tok.length>p.length&&tok.endsWith(p))return [tok.slice(0,-p.length),p];}return null;}
function findLemma(tok){if(SURFACE_BASE[tok])return SURFACE_BASE[tok];if(meanings.has(tok))return tok;const p=stripParticle(tok);if(p&&meanings.has(p[0]))return p[0];for(const [suf,baseType] of endings){if(tok.length>suf.length&&tok.endsWith(suf)){let st=tok.slice(0,-suf.length);const cs=[st,st+'다',st+'하다'];if(baseType==='하다')cs.unshift(st+'하다');for(const c of cs)if(meanings.has(c))return c;}}return null;}
function explain(tok){const p=stripParticle(tok);let lemma=findLemma(tok);let meaning=lemma?meanings.get(lemma):COMMON[tok]||'例文の日本語訳に対応する語・表現';let note=lemma&&lemma!==tok?`${tok} は ${lemma} の活用・語形です。`:'基本形または語彙形として使われています。';if(p){const base=p[0];lemma=findLemma(base)||base;meaning=meanings.get(lemma)||COMMON[base]||meaning;note=`${base} + ${p[1]}。${p[1]} は助詞として文中の関係を示します。`;}
for(const [suf,,desc] of endings){if(tok.endsWith(suf)&&tok.length>suf.length){note=desc+'。';break;}}
return {form:tok,base:lemma||tok,meaning_jp:meaning,pos:'語彙・語形',grammar_note:note};}
function wordsFor(ex){const toks=ex.match(/[가-힣]+/g)||[];return toks.map(explain);}
const priorExamples=new Set(PACK.filter(x=>x.example).map(x=>x.example.trim()));
const newExamples=new Set();
for(let i=0;i<100;i++){
 const r=ranks[i],s=SPECS[i],rank=START+i;if(r.rank!==rank)throw new Error(`rank sequence ${r.rank}`);
 const [meaning,jp,example,register,gr,note]=s;
 if(!meaning||!jp||!example||!register)throw new Error(`content missing @${rank}`);
 if(!/[가-힣]/.test(example))throw new Error(`Korean example missing @${rank}`);
 if(!/[ぁ-んァ-ヶ一-龠]/.test(jp))throw new Error(`Japanese translation missing @${rank}`);
 for(const g of gr)if(!G.has(g))throw new Error(`missing grammar ${g} @${rank}`);
 if(newExamples.has(example)||priorExamples.has(example))throw new Error(`duplicate example @${rank}: ${example}`);newExamples.add(example);
 const card={rank,word:r.word,meaning,example,example_jp:jp,grammar:gr.map(x=>G.get(x).name),grammar_ranks:gr,grammar_jp:gr.map(x=>`${G.get(x).name}：${G.get(x).definition||'既存文法データ参照'}`).join(' / '),register,ready:true,tts:example,words:wordsFor(example)};if(note)card.note=note;
 const idx=PACK.findIndex(x=>x.rank===rank);if(idx>=0)PACK[idx]=card;else PACK.push(card);
}
PACK.sort((a,b)=>a.rank-b.rank);
const arr=JSON.stringify(PACK);src=src.replace(/((?:const|let) PACK=)\[.*?\];\n/s,`$1${arr};\n`);
src=src.replace(/const APP_VERSION="[^"]*";/,`const APP_VERSION="${PATCH_VERSION}";`);
if(/const UPDATE_STAMP="[^"]*";/.test(src))src=src.replace(/const UPDATE_STAMP="[^"]*";/,`const UPDATE_STAMP="${UPDATE_STAMP}";`);else src=src.replace(/const APP_VERSION="[^"]*";/,m=>m+`\nconst UPDATE_STAMP="${UPDATE_STAMP}";`);
fs.writeFileSync(file,src);
const p2=src.match(/(?:const|let) PACK=(\[.*?\]);\n/s);if(!p2)throw new Error('PACK missing after write');const out=JSON.parse(p2[1]);
const slice=out.filter(x=>x.rank>=START&&x.rank<=END);if(slice.length!==100)throw new Error(`output count ${slice.length}`);
const rankSeen=new Set(),exampleSeen=new Map();
for(const c of out){if(rankSeen.has(c.rank))throw new Error(`duplicate rank ${c.rank}`);rankSeen.add(c.rank);if(c.example){const e=c.example.trim();if(exampleSeen.has(e))throw new Error(`duplicate example ranks ${exampleSeen.get(e)},${c.rank}`);exampleSeen.set(e,c.rank);}}
for(const c of slice){const rr=RANK.find(x=>x.rank===c.rank);if(!rr||rr.word!==c.word)throw new Error(`rank-word mismatch ${c.rank}`);for(const k of ['meaning','example','example_jp','grammar_jp','tts'])if(!c[k])throw new Error(`missing ${k} @${c.rank}`);if(c.tts!==c.example)throw new Error(`tts mismatch @${c.rank}`);if(!Array.isArray(c.words)||!c.words.length)throw new Error(`words missing @${c.rank}`);const toks=c.example.match(/[가-힣]+/g)||[];if(c.words.length!==toks.length)throw new Error(`token explanation count mismatch @${c.rank}`);for(const t of toks)if(!c.words.some(w=>w.form===t))throw new Error(`unexplained surface ${t} @${c.rank}`);for(const w of c.words)for(const k of ['form','base','meaning_jp','grammar_note'])if(!w[k])throw new Error(`word explanation ${k} missing @${c.rank}`);for(const g of c.grammar_ranks)if(!G.has(g))throw new Error(`broken grammar rank ${g} @${c.rank}`);}
const critical=['id="startBtn"','id="showAnswerBtn"','id="knownBtn"','id="saveSettingsBtn"','id="cloudSyncNowBtn"','id="exportBtn"','id="importProgress"','document.getElementById("startBtn").addEventListener("click"','document.getElementById("showAnswerBtn").addEventListener("click"','document.getElementById("knownBtn").addEventListener("click"','document.getElementById("saveSettingsBtn").addEventListener("click"','syncBtn.addEventListener("click",()=>syncCloudCore(true))','document.getElementById("exportBtn").addEventListener("click"','document.getElementById("importProgress").addEventListener("change"','korean-daily-3000-state-v01','korean-daily-3000-settings-v01','korean-daily-3000-sync-v01','function initCloudSync(','function syncCloudCore(','function queueCloudSave(','const READY=new Map(PACK.filter'];
for(const t of critical)if(before.includes(t)&&!src.includes(t))throw new Error(`regression token lost: ${t}`);
const keyRe=/localStorage\.(?:getItem|setItem|removeItem)\(([^)]+)\)/g;function keys(x){return [...x.matchAll(keyRe)].map(m=>m[1]).sort().join('|')}if(keys(before)!==keys(src))throw new Error('localStorage access keys changed');
const packPos=Math.max(src.indexOf('const PACK='),src.indexOf('let PACK='));const readyPos=src.indexOf('const READY=new Map(PACK.filter');if(!(packPos>=0&&readyPos>packPos))throw new Error('PACK initialization order broken');
console.log(`OK Rank ${START}-${END}: ${slice.length} cards; rank/dup/all-token/TTS/translation/grammar/persistence/cloud regression audits passed`);
