'use strict';
const fs=require('fs');const START=3701,END=3800,VERSION='1.5.7';
const file=process.argv[2]||'_site/index.html';let src=fs.readFileSync(file,'utf8');const candidates=require('./pack-3701-3800-v1.5.7.js');
function parse(name){const m=src.match(new RegExp(`(?:const|let)\\s+${name}=(\\[.*?\\]);`,'s'));if(!m)throw Error(name+' missing');return {m:m[0],d:JSON.parse(m[1])};}
const R=parse('RANK'),P=parse('PACK'),G=parse('GRAMMAR');const norm=s=>String(s||'').replace(/[-\\s]/g,'').trim();const seen=new Set(R.d.map(x=>norm(x.word))),priorEx=new Set(P.d.map(x=>String(x.example||'').trim()).filter(Boolean)),selected=[],selEx=new Set();
for(const row of candidates){if(!Array.isArray(row)||row.length<5)throw Error('bad candidate');const w=norm(row[0]),ex=String(row[2]||'').trim();if(!w||!ex||seen.has(w)||selected.some(x=>norm(x[0])===w)||priorEx.has(ex)||selEx.has(ex))continue;selected.push(row);selEx.add(ex);if(selected.length===100)break;}if(selected.length!==100)throw Error('only '+selected.length+' unique word/example candidates');
const maxOrig=Math.max(...R.d.map(x=>Number(x.orig)||0));const nr=selected.map((x,i)=>({rank:START+i,word:x[0],confidence:'中（Daily5000拡張）',orig:maxOrig+i+1}));const all=[...R.d,...nr];if(new Set(all.map(x=>norm(x.word))).size!==all.length)throw Error('duplicate RANK');src=src.replace(R.m,`const RANK=${JSON.stringify(all)};`);
const grammarRanks=new Set(G.d.map(x=>Number(x.rank))),baseGrammar=grammarRanks.has(9)?9:Number(G.d[0]?.rank||1);const clean=s=>String(s).replace(/^[“”‘’'"()[\\]{}]+|[.,!?。！？;:…~“”‘’'"()[\\]{}]+$/g,'');const particles=['에서는','으로부터','에게서','한테서','에게','한테','까지','부터','처럼','보다','으로','에서','과','와','랑','이랑','로','은','는','이','가','을','를','에','도','만','의'];
function noteToken(t){const c=clean(t);for(const p of particles)if(c.endsWith(p)&&c.length>p.length)return `${c}：${c.slice(0,-p.length)}＋助詞 ${p}`;if(/해야 해요$/.test(c))return `${c}：하다＋-아/어야 하다「〜しなければならない」の丁寧形`;if(/했어요$/.test(c))return `${c}：하다系用言の過去丁寧形 -했어요`;if(/됐어요$/.test(c))return `${c}：되다 の過去丁寧形 됐어요`;if(/았어요$|었어요$/.test(c))return `${c}：用言の過去丁寧形 -았/었어요`;if(/세요$/.test(c))return `${c}：丁寧な依頼・命令 -(으)세요`;if(/해요$|아요$|어요$/.test(c))return `${c}：用言の現在丁寧形 -아/어요`;if(/해서$|아서$|어서$/.test(c))return `${c}：理由・順序 -아/어서`;if(/니까$/.test(c))return `${c}：理由・発見の契機 -(으)니까`;if(/면$/.test(c))return `${c}：条件 -(으)면`;if(/려고$/.test(c))return `${c}：意図・目的 -(으)려고`;if(/고$/.test(c))return `${c}：接続語尾 -고`;return `${c}：例文中の語。日本語訳の対応箇所と合わせて基本意味・文中の役割を確認`;}
const cards=selected.map((r,i)=>{const [word,meaning,example,jp,note]=r,rank=START+i;const form_notes={};for(const t of example.split(/\\s+/).map(clean).filter(Boolean))form_notes[t]=noteToken(t);return {rank,word,meaning,example,example_jp:jp,jp,translation:jp,form_notes,grammar:[baseGrammar],grammar_ranks:[baseGrammar],grammar_links:[baseGrammar],grammar_point:'文法ワンポイント：해요体を中心に、例文内の助詞・活用をform_notesで確認。',note,word_notes:note,tts:example,tts_text:example,ready:true};});const pack=[...P.d,...cards];src=src.replace(P.m,`const PACK=${JSON.stringify(pack)};`);
for(const c of cards){if(!c.tts_text||!c.example_jp||!c.meaning||!c.word_notes||!Object.keys(c.form_notes).length)throw Error('card field missing '+c.rank);for(const t of c.example.split(/\\s+/).map(clean).filter(Boolean))if(!c.form_notes[t])throw Error('unexplained '+c.rank+':'+t);if(c.translation!==c.jp||c.tts_text!==c.example)throw Error('translation/tts mismatch '+c.rank);for(const gr of c.grammar_links)if(!grammarRanks.has(Number(gr)))throw Error('grammar link missing '+c.rank);}for(let r=START;r<=END;r++)if(!pack.some(c=>Number(c.rank)===r))throw Error('PACK rank missing '+r);
for(const key of ['korean-daily-3000-state-v01','korean-daily-3000-settings-v01','korean-daily-3000-sync-v01'])if(!src.includes(key))throw Error('storage/sync key missing '+key);for(const s of ['normalizeExampleToken','PACK','READY','function initCloudSync(','function syncCloudCore(','function queueCloudSave('])if(!src.includes(s))throw Error('core marker missing '+s);const packPos=src.search(/(?:const|let) PACK=/),readyPos=src.indexOf('const READY=new Map(PACK.filter');if(!(packPos>=0&&readyPos>packPos))throw Error('PACK/READY initialization order invalid');fs.writeFileSync(file,src);console.log(`Daily5000 ${VERSION}: Rank ${START}-${END} injected; selected=${selected.length}; RANK=${all.length}, PACK=${pack.length}`);