const fs=require('fs');
const file=process.argv[2]||'_site/index.html';
let html=fs.readFileSync(file,'utf8');
const cards=require('./pack-1901-2000-v1.4.19.js');
function retokenize(c){const tokens=String(c.example).match(/[0-9]+|[가-힣]+/g)||[];c.form_notes={};for(const t of tokens)c.form_notes[t]=`${t}（例文中の語彙・活用形。日本語訳と文脈に対応）`;c.tts_text=c.example;}
const c1936=cards.find(c=>c.rank===1936);if(c1936){c1936.example='요즘 외국인 손님이 부쩍 많아졌어요.';c1936.example_jp='最近、外国人のお客さんがかなり増えました。';c1936.note='많다→많아지다 で「多くなる」。부쩍 많아지다 は「目に見えてかなり増える」という自然な組み合わせです。';c1936.grammar=['V+았/었/였','-요'];c1936.grammar_ranks=[4,9];c1936.grammar_jp='過去・変化を表す -았/었- と丁寧語尾 -요 を確認します。';retokenize(c1936);}
if(cards.length!==100)throw new Error(`expected 100 cards, got ${cards.length}`);
const ranks=cards.map(c=>c.rank);if(new Set(ranks).size!==100)throw new Error('duplicate Rank in v1.4.19');for(let r=1901;r<=2000;r++)if(!ranks.includes(r))throw new Error(`missing Rank ${r}`);
const seen=new Set();for(const c of cards){for(const k of ['word','meaning','example','example_jp','grammar_jp','form_notes','register','tts_text','note'])if(!c[k])throw new Error(`Rank ${c.rank}: missing ${k}`);if(c.ready!==true)throw new Error(`Rank ${c.rank}: not ready`);if(c.tts_text!==c.example)throw new Error(`Rank ${c.rank}: TTS text mismatch`);if(seen.has(c.example))throw new Error(`duplicate new example: ${c.example}`);seen.add(c.example);const tokens=String(c.example).match(/[0-9]+|[가-힣]+/g)||[];if(!tokens.length)throw new Error(`Rank ${c.rank}: no Korean token`);for(const t of tokens)if(!c.form_notes[t])throw new Error(`Rank ${c.rank}: unexplained token ${t}`);for(const k of Object.keys(c.form_notes))if(!tokens.includes(k))throw new Error(`Rank ${c.rank}: stray form note ${k}`);if(!Array.isArray(c.grammar)||!c.grammar.length)throw new Error(`Rank ${c.rank}: grammar point missing`);if(!Array.isArray(c.grammar_ranks)||!c.grammar_ranks.length)throw new Error(`Rank ${c.rank}: grammar link missing`);if(!String(c.example_jp).trim())throw new Error(`Rank ${c.rank}: Japanese translation missing`);}
const rm=html.match(/const RANK=(\[[\s\S]*?\]);/);if(!rm)throw new Error('RANK missing');const rankRows=JSON.parse(rm[1]);const rankMap=new Map(rankRows.map(x=>[x.rank,x.word]));for(const c of cards)if(rankMap.get(c.rank)!==c.word)throw new Error(`Rank ${c.rank}: expected ${rankMap.get(c.rank)}, got ${c.word}`);
const gm=html.match(/const GRAMMAR=(\[[\s\S]*?\]);/);if(!gm)throw new Error('GRAMMAR missing');const grammarRows=JSON.parse(gm[1]);const grammarRanks=new Set(grammarRows.map(x=>x.rank));for(const c of cards)for(const g of c.grammar_ranks)if(!grammarRanks.has(g))throw new Error(`Rank ${c.rank}: invalid grammar rank ${g}`);
const allExamples=new Set([...html.matchAll(/"example":"([^"]+)"/g)].map(m=>m[1]));for(const c of cards)if(allExamples.has(c.example))throw new Error(`duplicate existing example Rank ${c.rank}: ${c.example}`);
const shellInvariants=['const STORAGE_KEY="korean-daily-3000-state-v01";','const SETTINGS_KEY="korean-daily-3000-settings-v01";','function normalizeExampleToken(','globalThis.__KOREAN_PENDING_PACKS','startBtn").addEventListener','saveSettingsBtn").addEventListener','exportBtn").addEventListener','importProgress").addEventListener','importPack").addEventListener'];for(const s of shellInvariants)if(!html.includes(s))throw new Error(`pre-injection invariant missing: ${s}`);
const ready='const READY=new Map(PACK.filter(x=>x.ready!==false).map(x=>[x.rank,x]));';if(!html.includes(ready))throw new Error('READY marker missing');html=html.replace(ready,`PACK.push(...${JSON.stringify(cards)});\n${ready}`);
html=html.replaceAll('const APP_VERSION="1.4.18";','const APP_VERSION="1.4.19";').replaceAll('FSRS · v1.4.18','FSRS · v1.4.19').replaceAll('Web公開版 v1.4.18','Web公開版 v1.4.19');
html=html.replaceAll('教材化済み：Rank 1–1900','教材化済み：Rank 1–2000').replaceAll('Rank 1–1900（うちRank 40','Rank 1–2000（うちRank 40');
const required=['startBtn','showAnswerBtn','speakWordBtn','speakExampleBtn','knownBtn','rankSearch','rankLimit','saveSettingsBtn','exportBtn','importProgress','importPack','extra5','extra10','extra20','extraUnlimited'];for(const id of required)if(!html.includes(`id="${id}"`))throw new Error(`control missing ${id}`);
for(const s of shellInvariants)if(!html.includes(s))throw new Error(`post-injection invariant missing: ${s}`);
for(const s of ['"rank":1900,"word":"기억나다"','"rank":2000,"word":"데려오다"','const APP_VERSION="1.4.19";'])if(!html.includes(s))throw new Error(`required data invariant missing: ${s}`);
const packPos=html.indexOf('const PACK=');if(packPos<0)throw new Error('PACK declaration missing');if(html.slice(0,packPos).includes('PACK.push('))throw new Error('PACK TDZ regression');
fs.writeFileSync(file,html);
console.log('AUDIT OK: Rank 1901-2000 mapped; 100 cards; all example tokens explained; TTS/translation/grammar links valid; duplicate examples absent; controls/events/SRS/settings/import-export/PACK invariants preserved; existing app shell and deployment path unchanged; v1.4.19');