const fs=require('fs');
const file=process.argv[2]||'_site/index.html';
let src=fs.readFileSync(file,'utf8');
const before=src,START=2101,END=2200,PATCH_VERSION='1.4.21',UPDATE_STAMP='2026-08-31';
function arrConst(name){const m=src.match(new RegExp(`const ${name}=(\\[.*?\\]);`,'s'));if(!m)throw Error(`${name} missing`);return JSON.parse(m[1]);}
const RANK=arrConst('RANK'),GRAMMAR=arrConst('GRAMMAR'),G=new Map(GRAMMAR.map(x=>[x.rank,x]));
const pm=src.match(/(?:const|let) PACK=(\[.*?\]);\n/s);if(!pm)throw Error('PACK missing');let PACK=JSON.parse(pm[1]);
const SPECS=require('./pack-2101-2200-v1.4.21.js');if(SPECS.length!==100)throw Error(`spec count ${SPECS.length}`);
const ranks=RANK.filter(x=>x.rank>=START&&x.rank<=END);if(ranks.length!==100)throw Error(`rank slice ${ranks.length}`);
const meanings=new Map(PACK.filter(x=>x?.word&&x?.meaning).map(x=>[x.word.replaceAll('-',''),x.meaning]));ranks.forEach((r,i)=>meanings.set(r.word.replaceAll('-',''),SPECS[i][0]));
const EXTRA={면접:'面接',자리:'席・場所',미리:'あらかじめ',브랜드:'ブランド',층:'階',바다:'海',공항:'空港',예정:'予定',그림:'絵',다양한:'多様な・いろいろな',문화:'文化',건강:'健康',홈페이지:'ホームページ',참가자:'参加者',국내산:'韓国産・国内産',소고기:'牛肉',충분하다:'十分だ',결정:'決定',행사:'行事・イベント',촛불:'ろうそく',햇빛:'日差し',기온:'気温',금액:'金額',입학하다:'入学する',전등:'照明',프로그램:'番組・プログラム',봉사단:'ボランティア団体',목소리:'声',컵:'コップ',천천히:'ゆっくり',퀴즈:'クイズ',이메일:'メール',안전:'安全',바닷가:'海辺',얼굴:'顔',바닥:'床',계단:'階段',계란말이:'卵焼き',새것:'新しいもの',약:'薬',교회:'教会',가시:'とげ',습관:'習慣',가격:'価格',영화:'映画',여름:'夏',산:'山',허브:'ハーブ',분위기:'雰囲気'};
for(const [k,v] of Object.entries(EXTRA))if(!meanings.has(k))meanings.set(k,v);
const P=['에서는','으로','에서','에게','한테','이랑','랑','에는','은','는','이','가','을','를','에','도','만','로','과','와','의'];
const E=[['했어요','하다','過去の丁寧形'],['해요','하다','現在の丁寧形'],['세요','다','丁寧な依頼・命令'],['었어요','다','過去の丁寧形'],['았어요','다','過去の丁寧形'],['어요','다','現在の丁寧形'],['아요','다','現在の丁寧形'],['고','다','動作・状態をつなぐ -고'],['면','다','条件 -(으)면'],['해서','하다','理由・順序 -해서'],['아서','다','理由・順序 -아서'],['어서','다','理由・順序 -어서'],['지','다','否定・確認などの接続語尾 -지'],['게','다','副詞化などの -게'],['는','다','現在連体形 -는'],['은','다','連体形 -(으)ㄴ'],['을','다','未来・予定の連体形 -(으)ㄹ']];
const S={부리지:'부리다',확보해:'확보하다',긴장해요:'긴장하다',좋아했어요:'좋아하다',하기:'하다',써요:'쓰다',내려다볼:'내려다보다',갈:'가다',일해요:'일하다',경험해:'경험하다',빌어요:'빌다',노려보지:'노려보다',기도해요:'기도하다',받고:'받다',생겼어요:'생기다',조심스러워요:'조심스럽다',떨어졌어요:'떨어지다',참가해요:'참가하다',달했어요:'달하다',참석해요:'참석하다',느려요:'느리다',강해요:'강하다',확인했어요:'확인하다',입학했어요:'입학하다',바꿨어요:'바꾸다',비춰요:'비추다',사과했어요:'사과하다',만족하고:'만족하다',시였어요:'이다',많아요:'많다',끝내면:'끝내다',머물러요:'머물다',활동하고:'활동하다',움직이는:'움직이다',결정해요:'결정하다',알아듣지:'알아듣다',쏟아:'쏟다',외웠어요:'외우다',바르면:'바르다',촉촉해요:'촉촉하다',걸어:'걷다',달려왔어요:'달려오다',맞히는:'맞히다',보내:'보내다',찍혔어요:'찍히다',분석해:'분석하다',정리했어요:'정리하다',부서졌어요:'부서지다',낼:'내다',그치면:'그치다',넘어지지:'넘어지다',뒤집어:'뒤집다',왔어요:'오다',갔어요:'가다',안았어요:'안다',대비해서:'대비하다',공부하고:'공부하다',만났어요:'만나다',어긴:'어기다',받았어요:'받다',찾아봐요:'찾아보다',녹아요:'녹다',예상돼요:'예상되다',계산해:'계산하다',올랐어요:'오르다',기르고:'기르다',묘해요:'묘하다',들었어요:'들다',와요:'오다',먹어요:'먹다',응원해요:'응원하다',박혔어요:'박히다',내뱉었어요:'내뱉다',알려:'알리다',달라요:'다르다',먹었어요:'먹다',푸르러요:'푸르다'};
function particle(t){for(const p of P)if(t.length>p.length&&t.endsWith(p))return[t.slice(0,-p.length),p];return null;}
function lemma(t){if(S[t])return S[t];if(meanings.has(t))return t;const pp=particle(t);if(pp){if(S[pp[0]])return S[pp[0]];if(meanings.has(pp[0]))return pp[0];}for(const [s,b] of E)if(t.length>s.length&&t.endsWith(s)){const st=t.slice(0,-s.length),cs=b==='하다'?[st+'하다',st,st+'다']:[st,st+'다',st+'하다'];for(const c of cs)if(meanings.has(c))return c;}return null;}
function explain(t){const pp=particle(t),l=lemma(t);let base=l||t,meaning=meanings.get(base)||EXTRA[base]||'例文訳に対応する語・表現',note=l&&l!==t?`${t} は ${l} の活用・語形です。`:'基本形または語彙形。';if(pp){base=lemma(pp[0])||pp[0];meaning=meanings.get(base)||EXTRA[base]||meaning;note=`${pp[0]} + ${pp[1]}。${pp[1]} は助詞として文中の関係を示します。`;}for(const [s,,d] of E)if(t.length>s.length&&t.endsWith(s)){note=`${t}：${d}。基本形 ${base}。`;break;}return{form:t,base,meaning_jp:meaning,pos:'語彙・語形',grammar_note:note};}
const wordsFor=e=>(e.match(/[가-힣]+/g)||[]).map(explain);
const priorExamples=new Set(PACK.filter(x=>x.example).map(x=>x.example.trim())),newExamples=new Set();
for(let i=0;i<100;i++){const r=ranks[i],rank=START+i,s=SPECS[i];if(r.rank!==rank)throw Error(`rank sequence ${r.rank}`);const[meaning,jp,example,register,gr,note]=s;if(!meaning||!jp||!example||!register)throw Error(`content missing @${rank}`);if(!/[가-힣]/.test(example)||!/[ぁ-んァ-ヶ一-龠]/.test(jp))throw Error(`language field mismatch @${rank}`);for(const g of gr)if(!G.has(g))throw Error(`missing grammar ${g} @${rank}`);if(priorExamples.has(example)||newExamples.has(example))throw Error(`new duplicate example @${rank}: ${example}`);newExamples.add(example);const card={rank,word:r.word,meaning,example,example_jp:jp,grammar:gr.map(g=>G.get(g).name),grammar_ranks:gr,grammar_jp:gr.map(g=>`${G.get(g).name}：${G.get(g).definition||'既存文法データ参照'}`).join(' / '),register,ready:true,tts:example,words:wordsFor(example)};if(note)card.note=note;const at=PACK.findIndex(x=>x.rank===rank);if(at>=0)PACK[at]=card;else PACK.push(card);}
PACK.sort((a,b)=>a.rank-b.rank);const packed=JSON.stringify(PACK);src=src.replace(/((?:const|let) PACK=)\[.*?\];\n/s,`$1${packed};\n`);src=src.replace(/const APP_VERSION="[^"]*";/,`const APP_VERSION="${PATCH_VERSION}";`);if(/const UPDATE_STAMP="[^"]*";/.test(src))src=src.replace(/const UPDATE_STAMP="[^"]*";/,`const UPDATE_STAMP="${UPDATE_STAMP}";`);else src=src.replace(/const APP_VERSION="[^"]*";/,m=>m+`\nconst UPDATE_STAMP="${UPDATE_STAMP}";`);fs.writeFileSync(file,src);
const outm=src.match(/(?:const|let) PACK=(\[.*?\]);\n/s);if(!outm)throw Error('PACK missing after write');const out=JSON.parse(outm[1]),slice=out.filter(x=>x.rank>=START&&x.rank<=END);if(slice.length!==100)throw Error(`output count ${slice.length}`);
const rankSeen=new Set();for(const c of out){if(rankSeen.has(c.rank))throw Error(`duplicate rank ${c.rank}`);rankSeen.add(c.rank);}const sliceExamples=new Set();for(const c of slice){if(sliceExamples.has(c.example))throw Error(`duplicate example in new slice ${c.rank}`);sliceExamples.add(c.example);const rr=RANK.find(x=>x.rank===c.rank);if(!rr||rr.word!==c.word)throw Error(`rank-word mismatch ${c.rank}`);for(const k of ['meaning','example','example_jp','grammar_jp','tts'])if(!c[k])throw Error(`missing ${k} @${c.rank}`);if(c.tts!==c.example)throw Error(`tts mismatch @${c.rank}`);const toks=c.example.match(/[가-힣]+/g)||[];if(!Array.isArray(c.words)||c.words.length!==toks.length)throw Error(`token explanation count @${c.rank}`);for(let i=0;i<toks.length;i++){if(c.words[i].form!==toks[i])throw Error(`surface mismatch ${toks[i]} @${c.rank}`);for(const k of ['form','base','meaning_jp','grammar_note'])if(!c.words[i][k])throw Error(`word ${k} missing @${c.rank}`);}for(const g of c.grammar_ranks)if(!G.has(g))throw Error(`broken grammar rank ${g} @${c.rank}`);}
const critical=['id="startBtn"','id="showAnswerBtn"','id="knownBtn"','id="saveSettingsBtn"','id="cloudSyncNowBtn"','id="exportBtn"','id="importProgress"','document.getElementById("startBtn").addEventListener("click"','document.getElementById("showAnswerBtn").addEventListener("click"','document.getElementById("knownBtn").addEventListener("click"','document.getElementById("saveSettingsBtn").addEventListener("click"','syncBtn.addEventListener("click",()=>syncCloudCore(true))','document.getElementById("exportBtn").addEventListener("click"','document.getElementById("importProgress").addEventListener("change"','korean-daily-3000-state-v01','korean-daily-3000-settings-v01','korean-daily-3000-sync-v01','function initCloudSync(','function syncCloudCore(','function queueCloudSave(','const READY=new Map(PACK.filter'];for(const t of critical)if(before.includes(t)&&!src.includes(t))throw Error(`regression token lost: ${t}`);
const kre=/localStorage\.(?:getItem|setItem|removeItem)\(([^)]+)\)/g,keyset=x=>[...x.matchAll(kre)].map(m=>m[1]).sort().join('|');if(keyset(before)!==keyset(src))throw Error('localStorage access keys changed');const packPos=Math.max(src.indexOf('const PACK='),src.indexOf('let PACK=')),readyPos=src.indexOf('const READY=new Map(PACK.filter');if(!(packPos>=0&&readyPos>packPos))throw Error('PACK initialization order broken');
console.log(`OK Rank ${START}-${END}: ${slice.length} cards; rank/new-duplicate/all-token/TTS/translation/grammar/SRS-settings/cloud/PACK audits passed`);
