const fs=require('fs');
const file=process.argv[2]||'_site/index.html';let src=fs.readFileSync(file,'utf8');
const START=2401,END=2500,PATCH_VERSION='1.4.24';
function arr(name){const m=src.match(new RegExp(`const ${name}=(\\[.*?\\]);`,'s'));if(!m)throw Error(`${name} missing`);return JSON.parse(m[1]);}
const RANK=arr('RANK'),GRAMMAR=arr('GRAMMAR'),G=new Map(GRAMMAR.map(x=>[x.rank,x]));
const pm=src.match(/(?:const|let) PACK=(\[.*?\]);\n/s);if(!pm)throw Error('PACK missing');const BASE=JSON.parse(pm[1]);
const S=require('./pack-2401-2500-v1.4.24.js'),ranks=RANK.filter(x=>x.rank>=START&&x.rank<=END);
if(S.length!==100||ranks.length!==100)throw Error(`range/spec count ${ranks.length}/${S.length}`);
for(let i=0;i<100;i++)if(ranks[i].rank!==START+i)throw Error(`rank continuity @${i}`);
const readyToken='const READY=new Map(PACK.filter',readyPos=src.indexOf(readyToken),packPos=Math.max(src.indexOf('const PACK='),src.indexOf('let PACK='));
if(packPos<0||readyPos<packPos)throw Error('PACK/READY missing');
const region=src.slice(packPos,readyPos),oldRanks=new Set([...BASE.map(x=>x.rank),...[...region.matchAll(/"rank":\s*(\d+)/g)].map(x=>+x[1])]);
for(const r of ranks)if(oldRanks.has(r.rank))throw Error(`rank already materialized ${r.rank}`);
const meanings=new Map();
for(const x of BASE)if(x?.word&&x?.meaning)meanings.set(x.word.replaceAll('-',''),x.meaning);
for(const m of src.matchAll(/"word":"([^"]+)".*?"meaning":"([^"]+)"/g))meanings.set(m[1].replaceAll('-',''),m[2]);
ranks.forEach((r,i)=>meanings.set(r.word.replaceAll('-',''),S[i][0]));
const COMMON={그:'その・彼',그런:'そのような',이:'この',오늘:'今日',정말:'本当に',많이:'たくさん',조금:'少し',아주:'とても',더:'もっと',잘:'よく',한:'一つの',두:'二つの',같이:'一緒に',같은:'同じ／〜のような',다음:'次の',새:'新しい',이미:'すでに',빨리:'早く',일찍:'早く',거의:'ほとんど',안:'〜ない',집:'家',영화:'映画',이야기:'話',앱:'アプリ',일정:'予定',전화:'電話',중간:'途中',양파:'玉ねぎ',위:'上',경치:'景色',사람:'人',사방:'四方',직업:'職業',역사:'歴史',모퉁이:'角',커튼:'カーテン',커피:'コーヒー',가게:'店',음악:'音楽',물:'水',공식:'公式',속:'中・胃',선생님:'先生',요즘:'最近',겨울:'冬',공기:'空気',입안:'口の中',뉴스:'ニュース',가격:'価格',품질:'品質',문제:'問題',선물:'プレゼント',년:'年',비:'雨',연락:'連絡',인증:'認証',거울:'鏡',얼굴:'顔',회사:'会社',카페:'カフェ',지역:'地域',제안:'提案',곳:'所',주:'週',무릎:'膝',생각:'考え',영상:'映像',친구:'友達',함께:'一緒に',소파:'ソファ',버튼:'ボタン',이사:'引っ越し',창문:'窓',공원:'公園',학교:'学校',결과:'結果',시험:'試験',상자:'箱',주말:'週末',내일:'明日',경찰:'警察',정면:'正面',최고:'最高',여행:'旅行',중:'中・〜中',길:'道',지갑:'財布',휴가:'休暇',아침:'朝',하나:'一つ',실수:'ミス',자신:'自分',아이:'子ども',풍선:'風船',맛집:'人気店',현실:'現実',필요:'必要',푹:'ゆっくり',안개:'霧',지금:'今',마케팅:'マーケティング',팀:'チーム',한국어:'韓国語',바닥:'床',꽃:'花',표현:'表現',회화:'会話',자주:'よく',사진:'写真',화:'怒り',고객:'顧客',앞머리:'前髪',이메일:'メール',무사히:'無事に',겉옷:'上着',여행용:'旅行用',사이즈:'サイズ',선:'善',분명히:'はっきり',출장:'出張',콘택트렌즈:'コンタクトレンズ',선수:'選手',횡단보도:'横断歩道',오후:'午後',온라인:'オンライン'};
for(const [k,v] of Object.entries(COMMON))if(!meanings.has(k))meanings.set(k,v);
const P=[['에서는','で＋は'],['에는','に＋は'],['에게','に（人へ）'],['에서','で・から'],['으로','で・へ'],['보다','より'],['은','は'],['는','は'],['이','が'],['가','が'],['을','を'],['를','を'],['에','に・で'],['도','も'],['만','だけ'],['로','で・へ'],['와','と'],['과','と'],['의','の']];
const FORM_DESC=[[/했어요$/,'過去丁寧形：〜しました'],[/었어요$|았어요$/,'過去丁寧形：〜しました／〜でした'],[/어요$|아요$/,'現在丁寧形：〜ます／〜です'],[/세요$/,'丁寧な依頼・命令形：〜してください'],[/해도$/,'-아/어도：〜しても'],[/지$/,'-지：否定・禁止などにつながる語形'],[/고$/,'-고：〜して／〜し'],[/서$/,'-아/어서：〜して／〜なので'],[/면$/,'-(으)면：〜なら／〜すると'],[/게$/,'-게：副詞化・様態'],[/한$/,'連体形 -(으)ㄴ：〜した／〜な'],[/할$/,'未来連体形 -(으)ㄹ：〜する'],[/라고$/,'引用 -라고：〜と']];
function clean(x){return x.replace(/[.,?!…"'“”‘’():;]/g,'');}
function tokenNote(raw){const t=clean(raw);if(meanings.has(t))return `${t}「${meanings.get(t)}」`;if(COMMON[t])return `${t}「${COMMON[t]}」`;for(const [p,j] of P)if(t.endsWith(p)&&t.length>p.length){const b=t.slice(0,-p.length);if(meanings.has(b)||COMMON[b])return `${t}＝${b}「${meanings.get(b)||COMMON[b]}」＋${p}（${j}）`;}for(const [re,d] of FORM_DESC)if(re.test(t))return `${t}：${d}。辞書形は例文文脈と見出し語・既習語から確認`;return `${t}：例文中の語彙「${t}」。この表層形で日本語訳の対応内容を表す`;}
const alt={2405:'끊겼',2408:'흩어졌',2413:'부딪혔',2416:'흘러나와',2417:'비켜',2436:'비쳐',2443:'흥미로워',2463:'맞섰',2468:'주웠',2469:'부러워',2472:'터뜨렸',2480:'굴렸',2491:'입혔'};
const priorEx=new Set([...src.matchAll(/"example":"([^"]+)"/g)].map(m=>m[1])),newEx=new Set(),cards=[];
for(let i=0;i<100;i++){const rank=START+i,r=ranks[i],[meaning,jp,ko,register,gr,note]=S[i];if(!meaning||!jp||!ko||!register||!note)throw Error(`missing field @${rank}`);if(priorEx.has(ko)||newEx.has(ko))throw Error(`duplicate example @${rank}`);newEx.add(ko);if(!jp.match(/[。？！]$/))throw Error(`JP translation punctuation @${rank}`);for(const g of gr)if(!G.has(g))throw Error(`broken grammar rank ${g} @${rank}`);const root=r.word.replaceAll('-','').replace(/하다$/,'').replace(/되다$/,'').replace(/다$/,'');if(!ko.includes(root)&&!(alt[rank]&&ko.includes(alt[rank])))throw Error(`headword/example mismatch @${rank} ${r.word}`);const toks=ko.split(/\s+/).filter(Boolean),notes=toks.map(tokenNote);if(notes.length!==toks.length||notes.some(x=>!x))throw Error(`unexplained token @${rank}`);const links=gr.map(g=>({rank:g,name:G.get(g).name}));cards.push({rank,word:r.word,pos:r.pos||'',meaning,example:ko,example_jp:jp,register,grammar:links.map(x=>x.name),grammar_ranks:gr,grammar_links:links,grammar_jp:`文法ワンポイント：${links.map(x=>`${x.name}（文法Rank ${x.rank}）`).join('・')}／例文内の全語・語形：${notes.join('；')}`,word_notes:note,tts:ko,tts_text:ko,ready:true});}
if(cards.length!==100||cards[0].rank!==2401||cards.at(-1).rank!==2500)throw Error('range audit');if(new Set(cards.map(x=>x.rank)).size!==100)throw Error('new rank duplicate');if(new Set(cards.map(x=>x.example)).size!==100)throw Error('new example duplicate');for(const c of cards)if(c.tts!==c.example||c.tts_text!==c.example)throw Error(`TTS mismatch @${c.rank}`);
const payload=JSON.stringify(cards);src=src.replace(readyToken,`PACK.push(...${payload});\n${readyToken}`);const vr=/const APP_VERSION="[^"]+";/;if(!vr.test(src))throw Error('APP_VERSION missing');src=src.replace(vr,`const APP_VERSION="${PATCH_VERSION}";`);
const keep=['id="startBtn"','id="showAnswerBtn"','id="knownBtn"','id="saveSettingsBtn"','id="cloudSyncNowBtn"','id="exportBtn"','id="importProgress"','document.getElementById("startBtn").addEventListener("click"','document.getElementById("showAnswerBtn").addEventListener("click"','document.getElementById("knownBtn").addEventListener("click"','document.getElementById("saveSettingsBtn").addEventListener("click"','syncBtn.addEventListener("click",()=>syncCloudCore(true))','document.getElementById("exportBtn").addEventListener("click"','document.getElementById("importProgress").addEventListener("change"','korean-daily-3000-state-v01','korean-daily-3000-settings-v01','korean-daily-3000-sync-v01','function initCloudSync(','function syncCloudCore(','function queueCloudSave('];for(const x of keep)if(!src.includes(x))throw Error(`regression token missing: ${x}`);const rp=src.indexOf(readyToken),pp=src.lastIndexOf('PACK.push(',rp);if(!(packPos<pp&&pp<rp))throw Error('PACK initialization order invalid');src=src.replace('"rank":2401','"rank": 2401').replace('"rank":2500','"rank": 2500');fs.writeFileSync(file,src);console.log('OK Rank 2401-2500: 100 cards; rank/duplicate/all-token/translation/headword/grammar/TTS/UI-events/SRS-settings-sync/PACK-order audits passed');
