'use strict';
const fs=require('fs');const START=4301,MAX_END=4400,VERSION='1.6.3a';const file=process.argv[2]||'_site/index.html';let src=fs.readFileSync(file,'utf8');
const rows=x=>Array.isArray(x)?x:String(x||'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map(x=>x.split('|'));const candidates=[...rows(require('./pack-4301-4400-v1.6.3.js')),...rows(require('./pack-4301-4400-extra-v1.6.3.js'))];
function parse(n){const m=src.match(new RegExp(`(?:const|let)\\s+${n}=(\\[.*?\\]);`,'s'));if(!m)throw Error(n+' missing');return{m:m[0],d:JSON.parse(m[1])};}const R=parse('RANK'),P=parse('PACK'),G=parse('GRAMMAR');const norm=s=>String(s||'').replace(/[-\s]/g,'').trim(),seen=new Set(R.d.map(x=>norm(x.word))),priorEx=new Set(P.d.map(x=>String(x.example||'').trim()).filter(Boolean)),selected=[],newEx=new Set();
for(const r of candidates){if(!Array.isArray(r)||r.length<5)throw Error('bad candidate');const w=norm(r[0]),e=String(r[2]||'').trim();if(!w||!e||seen.has(w)||selected.some(x=>norm(x[0])===w)||priorEx.has(e)||newEx.has(e))continue;selected.push(r);newEx.add(e);if(selected.length===100)break;}if(!selected.length)throw Error('no unique candidates');const END=START+selected.length-1;if(END>MAX_END)throw Error('range overflow');
const maxOrig=Math.max(...R.d.map(x=>Number(x.orig)||0)),nr=selected.map((x,i)=>({rank:START+i,word:x[0],confidence:'中（Daily5000拡張・日常実用性優先）',orig:maxOrig+i+1})),all=[...R.d,...nr];if(new Set(all.map(x=>norm(x.word))).size!==all.length)throw Error('duplicate RANK word');if(new Set(all.map(x=>Number(x.rank))).size!==all.length)throw Error('duplicate rank');src=src.replace(R.m,`const RANK=${JSON.stringify(all)};`);
const grammarRanks=new Set(G.d.map(x=>Number(x.rank))),baseGrammar=grammarRanks.has(9)?9:Number(G.d[0]?.rank||1),clean=s=>String(s).replace(/^[“”‘’'"()[\]{}]+|[.,!?。！？;:…~“”‘’'"()[\]{}]+$/g,''),particles=['에서는','으로부터','에게서','한테서','에게','한테','까지','부터','처럼','보다','으로','에서','과','와','랑','이랑','로','은','는','이','가','을','를','에','도','만','의'];
function noteToken(t){const c=clean(t);for(const p of particles)if(c.endsWith(p)&&c.length>p.length)return `${c}：${c.slice(0,-p.length)}＋助詞 ${p}`;if(/해야 해요$/.test(c))return `${c}：하다＋-아/어야 하다「〜しなければならない」`;if(/했어요$/.test(c))return `${c}：하다系用言の過去丁寧形`;if(/됐어요$/.test(c))return `${c}：되다の過去丁寧形`;if(/았어요$|었어요$/.test(c))return `${c}：用言の過去丁寧形 -았/었어요`;if(/세요$/.test(c))return `${c}：丁寧な依頼・命令 -(으)세요`;if(/해요$|아요$|어요$/.test(c))return `${c}：用言の現在丁寧形 -아/어요`;if(/해서$|아서$|어서$/.test(c))return `${c}：理由・順序 -아/어서`;if(/면$/.test(c))return `${c}：条件 -(으)면`;if(/려고$/.test(c))return `${c}：意図・目的 -(으)려고`;if(/고$/.test(c))return `${c}：接続語尾 -고`;return `${c}：例文内の語・語形。日本語訳との対応から基本意味と文中の役割を確認`;}
const cards=selected.map((r,i)=>{const[word,meaning,example,jp,note]=r,rank=START+i,form_notes={};for(const t of example.split(/\s+/).map(clean).filter(Boolean))form_notes[t]=noteToken(t);return{rank,word,meaning,example,example_jp:jp,jp,translation:jp,form_notes,grammar:[baseGrammar],grammar_ranks:[baseGrammar],grammar_links:[baseGrammar],grammar_point:'文法ワンポイント：해요体を中心に、例文内の助詞・活用をform_notesで確認。',note,word_notes:note,tts:example,tts_text:example,ready:true};}),pack=[...P.d,...cards];src=src.replace(P.m,`const PACK=${JSON.stringify(pack)};`);
for(const c of cards){if(!c.tts_text||!c.example_jp||!c.meaning||!c.word_notes||!Object.keys(c.form_notes).length)throw Error('field missing '+c.rank);for(const t of c.example.split(/\s+/).map(clean).filter(Boolean))if(!c.form_notes[t])throw Error('unexplained '+c.rank+':'+t);if(c.translation!==c.jp||c.jp!==c.example_jp||c.tts_text!==c.example||c.tts!==c.example)throw Error('translation/tts mismatch '+c.rank);for(const gr of c.grammar_links)if(!grammarRanks.has(Number(gr)))throw Error('grammar link missing '+c.rank);}for(let r=START;r<=END;r++)if(!pack.some(c=>Number(c.rank)===r))throw Error('PACK rank missing '+r);
for(const key of ['korean-daily-3000-state-v01','korean-daily-3000-settings-v01','korean-daily-3000-sync-v01'])if(!src.includes(key))throw Error('storage key missing '+key);for(const s of ['normalizeExampleToken','function initCloudSync(','function syncCloudCore(','function queueCloudSave(','id="startBtn"','id="showAnswerBtn"','id="knownBtn"','id="saveSettingsBtn"','id="cloudSyncNowBtn"'])if(!src.includes(s))throw Error('core marker missing '+s);const pp=src.search(/(?:const|let) PACK=/),rp=src.indexOf('const READY=new Map(PACK.filter');if(!(pp>=0&&rp>pp))throw Error('PACK/READY order invalid');fs.writeFileSync(file,src);console.log(`Daily5000 ${VERSION}: Rank ${START}-${END} injected; selected=${selected.length}; RANK=${all.length}, PACK=${pack.length}`);
