name: Extract next ranks temp
on:
  push:
    branches: ["main"]
permissions:
  contents: read
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract Rank 2101-2200
        run: node extract-next-ranks.js > next-ranks-2101-2200.json
      - name: Upload next ranks
        uses: actions/upload-artifact@v4
        with:
          name: next-ranks-2101-2200
          path: next-ranks-2101-2200.json
